# Generated by Django 3.1 on 2020-10-03 00:23

from django.db import migrations, models
import file_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=file_manager.models.get_file_path),
        ),
    ]
